### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by MvBonin** [coderedart/jokolay#20]
Please add a README.md in the base folder and write some basic information about this project there.
Maybe a screenshot if it is already in this state.

Seems to be an interesting project :) 
But some basic information in the root directory would be nice.

**Comment by coderedart** [comment]
I actually moved the repo to [gitlab](https://gitlab.com/coderedart/jokolay) because it had much more documentation regarding its features. there's actually a README, but it is outdated. you just need to go into the folder of the crate. https://gitlab.com/coderedart/jokolay/-/tree/marker_manager/jokolink for example has jokolink README. I will update the README soon for jokolay, and make this repo a mirror so it will show the update readme in github too. 

There's also a huge rewrite going on to port from opengl to vulkan for a couple reasons:
1. multiple windows (and multiple monitors) support was a very valid usecase, which means bye bye opengl (it is a mess with multi-threading), hello vulkan. egui itself is planning support for multiple windows which will lay the foundation for the much hyped "docking" feature. so, vulkan was a necessary move.
2. opengl performance in windows is garbage (was performing around 30% slower compared to linux). and this was on nvidia card whose drivers are supposed to be better than amd/intel's xD. I don't want to deal with opengl bugs which are much harder to debug.
once i get vulkan parts ready this week, it should be ready for an alpha release. then, i will start figuring out README and other documentations.
